apiVersion: security.accuknox.com/v1
kind: KubeArmorPolicy
metadata:
  name: mitre-tactic-Initial Access-Exploit-Public-Facing-Application
spec:
  selectorLabels:
    nodeSelector:
      hostname: xyz
  process:
    matchPaths:
      - path: /var/log/syslog
      - path: /var/log/messages
      - path: /var/log/secure
      - path: /var/log/samba
  action: Audit
  severity: 2
