apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: mitre-tactic-initial-acess-exploit-public-facing-application
  namespace: multiubuntu
spec:
  severity: 4
  selector:
    matchLabels:
      container: ubuntu-1
  file:
    matchDirectories:
      - dir: /etc/ssh/
      - dir: /var/log/
      - dir: /var/log/apt
      - dir: /var/log/apache2
  action: 
    Audit
