apiVersion: security.accuknox.com/v1
kind: KubeArmorPolicy
metadata:
  name: mitre-tactic-initial-acess-exploit-public-facing-application
  namespace: multiubuntu
spec:
  severity: 4
  selector:
    matchLabels:
      container: ubuntu-1
  file:
    matchPaths:
      - path: /var/log/syslog
      - path: /var/log/messages
      - path: /var/log/secure
      - path: /etc/ssh
  action: 
    Block
